[font]
size = 12.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "None"
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

# Uncomment to open Ubuntu on WSL.
# [shell]
# args = ["--cd ~"]
# program = 'C:\Windows\System32\wsl.exe'


# Dark mode.
[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"




# Light mode.
# [colors.primary]
# background = "#EFF1F5"
# foreground = "#4C4F69"
# dim_foreground = "#4C4F69"
# bright_foreground = "#4C4F69"
#
# [colors.cursor]
#
# text = "#EFF1F5"
# cursor = "#DC8A78"
#
#
# [colors.vi_mode_cursor]
# text = "#EFF1F5"
# cursor = "#7287FD"
#
#
# [colors.search.matches]
# foreground = "#EFF1F5"
# background = "#6C6F85"
#
# [colors.search.focused_match]
# foreground = "#EFF1F5"
# background = "#40A02B"
#
#
# [colors.footer_bar]
# foreground = "#EFF1F5"
# background = "#6C6F85"
#
#
# [colors.hints.start]
# foreground = "#EFF1F5"
# background = "#DF8E1D"
#
# [colors.hints.end]
# foreground = "#EFF1F5"
# background = "#6C6F85"
#
#
# [colors.selection]
# text = "#EFF1F5"
# background = "#DC8A78"
#
# [colors.normal]
# black = "#5C5F77"
# red = "#D20F39"
# green = "#40A02B"
# yellow = "#DF8E1D"
#
# blue = "#1E66F5"
#
# magenta = "#EA76CB"
# cyan = "#179299"
# white = "#ACB0BE"
#
# [colors.bright]
# black = "#6C6F85"
# red = "#D20F39"
# green = "#40A02B"
# yellow = "#DF8E1D"
# blue = "#1E66F5"
# magenta = "#EA76CB"
# cyan = "#179299"
# white = "#BCC0CC"
#
#
# [colors.dim]
# black = "#5C5F77"
# red = "#D20F39"
# green = "#40A02B"
# yellow = "#DF8E1D"
# blue = "#1E66F5"
# magenta = "#EA76CB"
# cyan = "#179299"
# white = "#ACB0BE"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#FE640B"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#DC8A78"
#
