" GENERAL OPTIONS
" ---------------
syntax on
set noerrorbells		    " Don't make any noises.
set tabstop=4 softtabstop=4	" Use 4 spaces for tabs,
set shiftwidth=4		    " Again, shift stuff but 4 spaces when using tab.
set expandtab			    " Convert a tab to spaces.
set smartindent			    " Try to indent for you, as much as Vim can.
set number relativenumber   " Enable sidebar numbers.
set smartcase			    " Do case sensitive searching until I put in a letter.
set noswapfile			    " Don't create vim.swp files all over the place.
set nobackup			    " Don't need backup, because we'll make our own.
set undodir=~/.vim/undodir	" Tell Vim where to save the undo directory.
set undofile			    " Create an undofile for every file we open/create.
set incsearch			    " While you search you get results.
set cursorline              " Highlights current line.
set background=dark         " Use $this terminal's dark theme.
" ---------------

" PLUG PLUGINS 
" -------------------------------------------
"  Try to install Plug, if it isn't already.
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Install these plugins.
call plug#begin('~/.vim/plugged')

    " Useful themes
    Plug 'morhetz/gruvbox'
    Plug 'connorholyday/vim-snazzy'

    "Git diff in the sidebar.
    Plug 'airblade/vim-gitgutter'

    " Make undoing stuff easier.
    Plug 'mbbill/undotree'      

call plug#end()
" -------------------------------------------



" THEMES
" ------
" Use the Gruvbox theme.
autocmd vimenter * ++nested colorscheme gruvbox
" colorscheme snazzy
" ------



" KEY MAPS & KEY HACKS 
" -----------------------------------------------
" Sets the leader (command key) to spacebar.
let mapleader = " "

" Keep the cursor in the center of the screen.
nnoremap j jzz
nnoremap k kzz

" Open the undo tree.
nnoremap <leader>u :UndotreeShow<CR>

" Navigate around open files.
nnoremap <leader>h :wincmd h<CR>
nnoremap <leader>j :wincmd j<CR>
nnoremap <leader>k :wincmd k<CR>
nnoremap <leader>l :wincmd l<CR>

" Format/indent the entire file, from the top.
nnoremap <leader>f gg=G<CR>

" Toggle word-wrap.
nnoremap <leader>ww :set wrap!<CR>

" Create new window, open file browser, set window to 25%.
nnoremap <leader>pv :wincmd v<bar> :Ex <bar> :vertical resize 25<CR>

" If you accidentally use W or Q, it doesn't matter.
:command WQ wq
:command Wq wq
:command W w
:command Q q

" WSL yank support
let s:clip = '/mnt/c/Windows/System32/clip.exe'
if executable(s:clip)
    augroup WSLYank
        autocmd!
        autocmd TextYankPost * if v:event.operator ==# 'y' | call system('cat |' . s:clip, @0) | endif 
    augroup END
endif
" -----------------------------------------------

