[font]
size = 14.0

[font.glyph_offset]
x = 0
y = 3

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 6

[window]
decorations = "None"
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 8
y = 8
